# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
