# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 14:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_site_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
