# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0007_auto_20161228_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
