# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0008_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='main_header_of_site',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.Category'),
        ),
    ]
