# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0009_auto_20161229_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='only_log_in',
            new_name='only_for_log_in',
        ),
    ]
