# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0013_auto_20161229_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='main_header_of_site',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
