# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 23:27
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0015_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100),
        ),
    ]
